version: '3.4'

services:

  my-finance-pal-web:
    ports:
      - 9000:80
    build:
      args:
        - Configuration=Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  bank-integration-api:
    ports:
      - 8000:80
    env_file:
    - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      NORDIGEN_SECRET_ID: ${NORDIGEN_SECRET_ID}
      NORDIGEN_SECRET_KEY: ${NORDIGEN_SECRET_KEY}
    restart: on-failure
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  assets-service-api:
    ports:
      - 8001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      INTEGRATION__BANKAPI: http://bank-integration-api
      DATABASES__ASSETSDB__CONNECTIONSTRING: "User ID=dbuser;Password=P@ssw0rd;Server=assets-db;Port=5432;Database=AssetsDb;Integrated Security=true;Pooling=true;"
      DATABASES__ASSETSDB__FORCEINIT: "true"
    restart: on-failure
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  assets-db:
    ports:
      - 40000:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - assets-db-data:/var/lib/postgresql/data

volumes:
  assets-db-data: {}
    
