version: '3.4'

services:

  bank-integration-api:
    ports:
      - 8000:80
    env_file:
    - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      NORDIGEN_SECRET_ID: ${NORDIGEN_SECRET_ID}
      NORDIGEN_SECRET_KEY: ${NORDIGEN_SECRET_KEY}
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  assets-service-api:
    ports:
      - 8001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      INTEGRATION__BANKAPI: http://bank-integration-api
      DATABASES__ASSETSDB__CONNECTIONSTRING: "User ID=dbuser;Password=P@ssw0rd;Server=assets-db;Port=5432;Database=AssetsDb;Integrated Security=true;Pooling=true;"
      DATABASES__ASSETSDB__FORCEINIT: "true"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  assets-db:
    ports:
      - 40000:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=P@ssw0rd
    
