version: '3.4'

services:

  my-finance-pal-web:
    image: my-finance-pal/mfp-webapp
    build:
      context: src/Web/MyFinancePal
      dockerfile: ./Dockerfile
    depends_on:
      - assets-service-api

  bank-integration-api:
    image: my-finance-pal/bank-integration-api
    build:
      context: src/Integration/BankIntegration/BankIntegration.API
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN:

  assets-service-api:
    image: my-finance-pal/assets-service-api
    build:
      context: src/Services/AssetsService/AssetsService.API
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN:
    depends_on:
      - assets-db
      - bank-integration-api

  assets-db:
    image: postgres:14.2-alpine 
