name: "Build an test for dotnet"
description: "Builds dotnet code webapi project and runs unit tests"

inputs:
  workdir:
    description: "Working dir to run commands"
    default: src/
    required: false
  project:
    description: "Project to build"
    required: true
  test-project:
    description: "Project to build"
    required: true
  configuration:
    description: "Build configuration"
    default: Release
    required: false
  github-token:
    description: "Add GITHUB_TOKEN to compilation"
    required: false
    default: "dummy"

runs:
  using: "composite"
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 6.0.x
   
  - name: Initialize CodeQL
    uses: github/codeql-action/init@v2
    with:
     languages: csharp
     config-file: ./.github/codeql/codeql-config.yml

  - name: Restore dependencies
    shell: bash
    working-directory: ${{ inputs.workdir }}
    run: |
      dotnet restore ${{ inputs.project }}
      dotnet restore ${{ inputs.test-project }}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      
  - name: Build
    shell: bash
    working-directory: ${{ inputs.workdir }}
    run: |
      dotnet build --no-restore ${{ inputs.project }} /p:UseSharedCompilation=false -c ${{ inputs.configuration }}
      dotnet build --no-restore ${{ inputs.test-project }} /p:UseSharedCompilation=false -c ${{ inputs.configuration }}

  - name: Test
    shell: bash
    working-directory: ${{ inputs.workdir }}
    run: dotnet test --no-build ${{ inputs.test-project  }} --verbosity normal --logger "trx;LogFileName=test-results.trx" -c ${{ inputs.configuration }}
      
  - name: Test Report
    uses: dorny/test-reporter@v1
    if: always()
    with:
      name: Tests Results
      path: '**/TestResults/*.trx'
      reporter: dotnet-trx

  - name: Perform CodeQL Analysis
    uses: github/codeql-action/analyze@v2
  




