name: libs-globalframework

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - 'src/Libs/GlobalFramework/**'
      - '.github/workflows/libs-globalframework.yml'
  push:
    branches:
    - main
    paths:
      - 'src/Libs/GlobalFramework/**'
      - '.github/workflows/libs-globalframework.yml'

jobs:
  build-pack-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: ./.github/workflows/composite/build-dotnet
      with:
        workdir: 'src/Libs/GlobalFramework/'
        project: 'GlobalFramework.csproj'

    - uses: ./.github/workflows/composite/nuget-pack-push
      if: ${{ github.event_name != 'pull_request' }}
      with:
        project: 'src/Libs/GlobalFramework/GlobalFramework.csproj'
        package-source: github
        github-token: ${{ secrets.GITHUB_TOKEN }}