name: services-assets-api

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - 'src/Services/AssetsService/AssetsService.API/**'
      - '.github/workflows/service-assets-api.yml'
  push:
    branches:
    - main
    paths:
      - 'src/Services/AssetsService/AssetsService.API/**'
      - '.github/workflows/service-assets-api.yml'

env:
  IMAGE_TAG: ${{ github.run_id }}.${{ github.run_number }}
  SERVICE_NAME: assets-service-api

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - uses: ./.github/workflows/composite/build-test-dotnet
      name: Build, scan and test code
      with:
        project: 'Services/AssetsService/AssetsService.API/AssetsService.API.csproj'
        test-project: 'Services/AssetsService/AssetsService.API.Tests/AssetsService.API.Tests.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
  docker-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: build-test

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/docker-push
      with:
        context: 'Services/AssetsService/AssetsService.API/'
        registry: ghcr.io
        registry-username: ${{ github.actor }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-tag: 'ghcr.io/theonorg/my-finance-pal/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}'
